# Generated by Django 4.0.4 on 2022-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='numberOfQuestions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
