# Generated by Django 4.0.4 on 2022-05-01 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_recipient'),
        ('quiz', '0007_quiz_numberofquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='attempts',
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('attempts', models.PositiveIntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
