# Generated by Django 4.0.4 on 2022-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_quiz_attempts_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Attempts',
        ),
    ]
