# Generated by Django 4.0.4 on 2022-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_result_pass_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='marksToPass',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='numberOfQuestions',
            field=models.PositiveIntegerField(),
        ),
    ]
