# Generated by Django 4.0.4 on 2022-05-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_quiz_markstopass_alter_quiz_numberofquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='numberOfQuestions',
        ),
    ]
