# Generated by Django 4.0.4 on 2022-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
