# Generated by Django 4.0.4 on 2022-05-08 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_is_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_pass',
        ),
    ]
