# Generated by Django 4.0.4 on 2022-05-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_is_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
