# Generated by Django 4.0.4 on 2022-04-24 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_lessons_lesson_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('videolink', models.CharField(max_length=11)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lessons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
            ],
        ),
    ]
