# Generated by Django 4.0.4 on 2022-04-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='title',
        ),
    ]
