# Generated by Django 4.0.4 on 2022-04-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_name_lesson_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
