# Generated by Django 4.0.4 on 2022-04-25 00:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_name_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videolink',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
