# Generated by Django 4.0.4 on 2022-04-26 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_video_videolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('publish_year', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='books/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='books',
            field=models.ManyToManyField(blank=True, to='courses.book'),
        ),
    ]
