# Generated by Django 4.0.4 on 2022-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_book_lesson_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
