# Generated by Django 4.0.4 on 2022-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_lesson_books_book_lessons_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='books',
            field=models.ManyToManyField(blank=True, to='courses.book'),
        ),
    ]
