# Generated by Django 4.0.4 on 2022-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_lesson_books_book_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lessons',
        ),
        migrations.AddField(
            model_name='video',
            name='books',
            field=models.ManyToManyField(blank=True, to='courses.book'),
        ),
    ]
