# Generated by Django 4.0.4 on 2022-04-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_book_lessons_video_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='books',
        ),
        migrations.AddField(
            model_name='lesson',
            name='books',
            field=models.ManyToManyField(blank=True, to='courses.book'),
        ),
    ]
