# Generated by Django 4.0.4 on 2022-04-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_video_books_lesson_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson'),
        ),
    ]
