# Generated by Django 4.0.4 on 2022-04-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_lesson_courses_alter_lesson_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz',
        ),
    ]
