# Generated by Django 4.0.4 on 2022-05-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
