# Generated by Django 4.0.4 on 2022-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_rename_user_review_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
