# Generated by Django 4.0.4 on 2022-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='material/'),
        ),
    ]
