# Generated by Django 4.0.4 on 2022-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
